"""empty message

Revision ID: 94109c2796e3
Revises: 9ef235a9daf4
Create Date: 2026-04-02 11:11:32.222579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94109c2796e3'
down_revision = '9ef235a9daf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint')
    # ### end Alembic commands ###
